server:
  port: 8000
  shutdown: GRACEFUL

spring:
  application:
    name: s3-replication-server
  cassandra:
    contact-points: "localhost:9042"
    keyspace-name: s3_replication
    password: "cassandra"
    username: "cassandra"
    schema-action: none
    local-datacenter: datacenter1

jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
  validityInMs: 3600000 # 1 hour
  refreshValidityInMs: 2592000000 # 30 days
s3:
  replicationJobDelay: 60_000 # ms
  threads: 10
  buckets:
    - host: https://storage.yandexcloud.net
      bucket: ""
      accessKey: ""
      secretKey: ""
      region: ru-central1
    - host: https://storage.yandexcloud.net
      bucket: ""
      accessKey: ""
      secretKey: ""
      region: ru-central1



logging:
  pattern:
    console: "%d - %t - %5p [%8c] - %m %n"
    file: "%d - %t - %5p [%8c] - %m %n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      file-name-pattern: ${log.dir:./}/s3-replication-server.main.%d.%i.log.gz
      max-history: 28
  file:
    name: ${log.dir:./}/s3-replication-server.main.log
  level:
    web: debug
